### PR TITLE
Sort faostat by date accessed

### PR DESCRIPTION
**Pull request by pabloarosado**
**UPDATE**: I would suggest to cancel this PR and instead continue on [this PR](https://github.com/owid/walden/pull/32).

This PR would be an alternative to [this other PR](https://github.com/owid/walden/pull/27/files).
~* Store downloaded FAOstat files in a folder based on `date_accessed` instead of `publication_date` or `modification_date`.~
~TODO: To avoid downloading many times the same files, we could first check if a certain dataset already exists in index with the same `publication_date` and `modification_date`. If so, skip.~
~* Avoid downloading a dataset if a file with the same `source_data_url`, `publication_date` and `modification_date` (if given) already exists in walden index.~
* Store downloaded FAOstat files in a folder based on `version` (which is set to `date_accessed`) instead of `publication_date`.
* Avoid downloading a dataset if a file with the same `source_data_url` already exists in walden index, with a `date_accessed` more recent than the latest modification date of the dataset.

### CODE REVIEW

**Review by Marigold — APPROVED** [review]
Looks good

**Review by Marigold — APPROVED** [review]

**Review by larsyencken — COMMENTED** [review]
It occurs to me that the main reason for `date_accessed` is in case they modify the data, so `date_accessed` and `modification_date` are kind of the same thing? Maybe we don't need two fields?

I like the saving things into walden using a date-accessed path though, that will avoid overwrites.

**Comment by pabloarosado** [comment]
Thanks @larsyencken , I think `publication_date`, `modification_date` and `date_accessed` are conceptually different things, all of them potentially useful (although `modification_date` is indeed less useful). In the FAOstat case, as you can see, I am checking if a dataset needs to be updated based on whether the `modification_date` has changed. If we don't have access to that field, we would be downloading the same dataset every time we do an update (which is not a big deal, but eventually it could be a lot of unnecessary data that we are downloading every time).

**Comment by larsyencken** [comment]
> If we don't have access to that field, we would be downloading the same dataset every time we do an update (which is not a big deal, but eventually it could be a lot of unnecessary data that we are downloading every time).

That's only by convention. For FAO, we would simply compare `last-modified` header with `date_accessed` and we have the same behaviour that you wanted now, but just with existing fields, no?

**Comment by pabloarosado** [comment]
> > If we don't have access to that field, we would be downloading the same dataset every time we do an update (which is not a big deal, but eventually it could be a lot of unnecessary data that we are downloading every time).
> 
> That's only by convention. For FAO, we would simply compare `last-modified` header with `date_accessed` and we have the same behaviour that you wanted now, but just with existing fields, no?

I think you are right. OK, in that case I will change the code to remove `modification_date`, both in this and in [the other PR](https://github.com/owid/walden/pull/29).

**Comment by larsyencken** [comment]
Thanks Pablo! No other comments from me, good to ship after that!

**Pull request closed without merging**
